apiVersion: v1
kind: ConfigMap
metadata:
  name: client-script
  namespace: default
data:
  client.sh: |
    #!/bin/sh
    set -e

    #/root/client &> /tmp/curl-client.log
    #while true; do
    for i in $(seq 0 9) ; do
      #URL="http://strigazi-cc7-builder:14000/sayhello/Spyros"
      #URL="http://go-server:14000/sayhello/Spyros"
      #URL="http://go-server-employees.cern.ch/employees/10001"
      #URL="http://go-server-employees.cern.ch/employees/$(shuf -i 10001-499990 -n 1)"
      #_base_url="http://str18-8-1.cern.ch/go-server/sayhello/spyros"
      #_base_url="https://cmsweb-testbed.cern.ch/crabserver/preprod/info"
      _base_url="https://cmsweb-testbed.cern.ch/dbs/int/global/DBSReader/datasets?detail=False"
      #for _base_url in $(cat /data/url-4-imran-k8s-tests.txt) ; do 
          curl \
              -s \
              --cert /certs/cms-proxy.pem \
              --cacert /certs/cms-proxy.pem \
              --cacert /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem \
              -w "${_base_url} %{http_code} %{remote_ip} %{time_total}\n" \
              -o /dev/null \
              "${_base_url}" | tee --append --ignore-interrupts /tmp/curl-client.log
      #done
      #sleep 0.1s
    done
    echo "Finished. sleeping 100d"
    sleep 100d

  logrotate.conf: |
    /tmp/curl-client.log {
        rotate 0
        copytruncate
        size 10M
        missingok
        nocompress
    }
  grok-config.yml: |
    global:
      config_version: 3
    input:
      type: file
      path: /tmp/curl-client.log
      fail_on_missing_logfile: false
    imports:
    - type: grok_patterns
      dir: ./patterns
    metrics:
    - type: histogram
      name: curl_client_request
      help: Curl client request response times
      match: '%{DATA:rawrequest} %{NUMBER:http_code} %{IP:remoteip} %{NUMBER:time_total}'
      value: '{{.time_total}}'
      labels:
        http_code: '{{.http_code}}'
        rawrequest: '{{.rawrequest}}'
        remoteip: '{{.remoteip}}'
    - type: counter
      name: curl_client_request_counter
      help: Curl client request response counter
      match: '%{DATA:rawrequest} %{NUMBER:http_code} %{IP:remoteip} %{NUMBER:time_total}'
      labels:
        http_code: '{{.http_code}}'
        rawrequest: '{{.rawrequest}}'
        remoteip: '{{.remoteip}}'
    server:
      protocol: http
      port: 9144

