---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: default
  labels:
    k8s-app: curl-client
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: curl-client
  template:
    metadata:
      labels:
        k8s-app: curl-client
    spec:
      #nodeName: str-loader-2xlarge-24s5kpxs7xad-node-0
      #hostNetwork: true
      containers:
      - name: curl-client
        #image: centos:8
        image: registry.fedoraproject.org/fedora:33
        imagePullPolicy: "IfNotPresent"
        command: ['/bin/bash', '-c']
        args: ['/client.sh']
        #args: ['for i in $(seq 1 10) ; do /client.sh & done ; echo "sleeping 60m" ; sleep 60m']
        volumeMounts:
          - name: workspace
            mountPath: /tmp
          - name: client-cm
            mountPath: /client.sh
            subPath: client.sh
          - mountPath: /etc/
            name: etc-grid-security
          - name: cms-proxy
            mountPath: /certs
          - name: urls
            mountPath: /data
      - name: grok
        image: gitlab-registry.cern.ch/strigazi/containers/grok_exporter
        imagePullPolicy: "IfNotPresent"
        command:
        - grok_exporter
        - -config
        - /grok-config.yml
        #ports:
        #- containerPort: 9144
        volumeMounts:
          - name: workspace
            mountPath: /tmp
          - name: client-cm
            mountPath: /grok-config.yml
            subPath: grok-config.yml
      - name: logrotate
        image: gitlab-registry.cern.ch/strigazi/containers/logrotate:centos8
        imagePullPolicy: "IfNotPresent"
        command:
        - sleep
        args:
        - 100d
      securityContext:
        seLinuxOptions:
          type: "spc_t"
      volumes:
      - name: workspace
        emptyDir:
      - name: client-cm
        configMap:
          name: client-script
          defaultMode: 0755
      - name: urls
        configMap:
          name: urls
          defaultMode: 0755
      - name: etc-grid-security
        hostPath:
          path: /etc/
      - name: cms-proxy
        secret:
          secretName: cms-proxy
