---
apiVersion: v1
kind: Service
metadata: 
  name: curl-client
  namespace: go-server
  labels: 
    k8s-app: curl-client
spec: 
  ports: 
    - port: 9144
      protocol: TCP
      name: metrics
  selector: 
    k8s-app: curl-client

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata: 
  name: curl-client
  namespace: go-server
  labels: 
    release: prometheus-operator
    k8s-app: curl-client
spec: 
  endpoints: 
  - path: /metrics
    port: metrics
    interval: 5s
  jobLabel: "app.kubernetes.io/name"
  namespaceSelector: 
    matchNames: 
    - go-server
  selector: 
    matchLabels: 
      k8s-app: curl-client
